apiVersion: source.toolkit.fluxcd.io/v1beta2 # or v1 depending on your Flux version
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx