apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 5m
  chart:
    spec:
      chart: mealie
      version: '5.1.0'
      sourceRef:
        kind: HelmRepository
        name: mealie-charts
        namespace: flux-system
  values:
    image:
      repository: hkotel/mealie
      tag: latest
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
        - host: mealie.local
          paths:
            - path: /
              pathType: Prefix