apiVersion: helm.toolkit.fluxcd.io/v2beta1 # or v2 depending on your Flux version
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx # Deploy Nginx into its own namespace
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.10.1" # Check for the latest version
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      service:
        # For Talos, you might need LoadBalancer service type if your CNI supports it,
        # or NodePort and then configure external access to a node's IP and the NodePort.
        # If your Talos is on a cloud provider that provides LoadBalancers, this is easier.
        # For bare-metal, you might need something like MetalLB or use NodePort.
        type: NodePort
      # consider replica count for HA
      # replicaCount: 2
      kind: DaemonSet # Ensures an ingress controller runs on each node, good for NodePort/HostPort
      hostPort:
        enabled: true # If using NodePort/HostPort
      tolerations: # Add tolerations if your Talos nodes have taints (e.g., control plane taints)
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"