apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  values:
    persistence:
      enabled: true
      size: 10Gi
    ingress:
      hosts:
        - host: mealie.local